# Models records
base_bw:
  hidden_dim: 32
  nb_hidden_layers: 3
  z_dim: 32
  nb_channels: 1
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.
  inner_activation: tanh
  inner_architecture_key: base
base_rbg:
  hidden_dim: 32
  nb_hidden_layers: 4
  z_dim: 32
  nb_channels: 3
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.5
  inner_activation: tanh
  inner_architecture_key: base